trigger:
- main

pool:
  name: Default   # your Azure DevOps agent pool name

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: "Use .NET SDK 9"
  inputs:
    packageType: "sdk"
    version: "9.x"

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
