trigger:
- main

pool:
  name: Default

variables:
  buildConfiguration: 'Release'
  azureServiceConnection: 'Azure subscription 1 (1373009b-21ce-4af1-994f-6fd349b36266)'
  webAppName: 'movieshopp'
  projectToPublish: 'MovieShopMVC/MovieShopMVC.csproj'   # <-- set this to your web project

steps:
- task: UseDotNet@2
  displayName: "Use .NET SDK 9"
  inputs:
    packageType: "sdk"
    version: "9.x"

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    projects: '$(projectToPublish)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'
    zipAfterPublish: true

- task: AzureWebApp@1
  displayName: Deploy to Azure App Service
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)/publish/**/*.zip'
